### PR TITLE
Fix: Issue #330 empty query params

### LINKED ISSUE #330: Unpredictable output from `getQueryParams`
**Describe the bug**

If the `url` parameter given to `getQueryParams` does not contain query parameters, the method outputs an object with the full path as a key instead.

**To Reproduce**

```javascript
import { getQueryParams } from '@tinyhttp/url';

console.log(getQueryParams('/hello'));
console.log(getQueryParams('/hello?world=42'));
```

The above code yields:

```
{ '/hello': '' }
{ world: '42' }
```

**Expected behavior**

I would expect `getQueryParams` to yield an empty object for a `url` string that does not contain any query params.

```
{ }
{ world: '42' }
```

**Versions**

- `node`: 14.18.1
- `@tinyhttp/app`: 2.0.11

### PR DESCRIPTION
**Pull request by SaiKiranMukka**
closes #330 
returns empty object ('{}') if no query params found

### CODE REVIEW

File: packages/url/src/index.ts [hunk 1]
```diff
@@ -22,10 +22,11 @@ export type URLParams = {
...
-export const getPathname = (u: string): string => {
-  const end = u.indexOf('?')
+export const getPathname = (url: string): string => url.slice(0, getQueryIndex(url))
 
-  return u.slice(0, end === -1 ? u.length : end)
-}
+export const getQueryParams = (url = '/'): ParsedUrlQuery => parse(url.slice(getQueryIndex(url) + 1))
 
-export const getQueryParams = (url = '/'): ParsedUrlQuery => parse(url.slice(url.indexOf('?') + 1))
+const getQueryIndex = (url: string): number => {
```
Comment (talentlessguy) [inline packages/url/src/index.ts:29]: pla declare this function before using it

Comment (SaiKiranMukka) [reply packages/url/src/index.ts:25]: Updated with new commit

**Comment by talentlessguy** [comment]
@all-contributors add @SaiKiranMukka for code
